#!/usr/bin/env bash
# gen-cursor.sh — generate the committed .cursor/ bundle + AGENTS.md from the canonical
# Claude Code sources (CLAUDE.md, rules/RULES.md, .claude/skills, .claude/commands, the
# protect-paths hook). One source of truth: edit those, then `make cursor`.
# Adapted from tarnn/claude scripts/gen-cursor.sh (simplified: no plugins/agents/globs).
#
# Usage:  gen-cursor.sh          # (re)generate in place
#         gen-cursor.sh --check  # regenerate to a temp dir and diff; nonzero on drift
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECK=0; [ "${1:-}" = "--check" ] && CHECK=1
OUT="$REPO/.cursor"
if [ "$CHECK" = 1 ]; then OUT="$(mktemp -d)/.cursor"; fi
mkdir -p "$OUT/rules" "$OUT/commands"

require_fm() { # fail loudly if frontmatter isn't properly delimited
  local n
  n="$(grep -c '^---[[:space:]]*$' "$1" 2>/dev/null || echo 0)"
  if [ "${n:-0}" -lt 2 ]; then
    echo "✗ gen-cursor: $1 is missing '---' frontmatter delimiters" >&2
    exit 1
  fi
}
fm_field() { # fm_field <file> <field>
  awk -v f="$2" 'BEGIN{c=0}
    /^---[[:space:]]*$/ {c++; if(c==2) exit; next}
    c==1 && $0 ~ "^"f":" { sub("^"f":[[:space:]]*",""); print; exit }' "$1"
}
fm_body() { # everything after the closing --- (files without frontmatter pass through)
  if grep -q '^---[[:space:]]*$' "$1"; then
    awk 'BEGIN{c=0} /^---[[:space:]]*$/{c++; next} c>=2{print}' "$1"
  else
    cat "$1"
  fi
}
emit_rule() { # emit_rule <outfile> <description|""> <always:true|false> <bodyfile>
  local out="$1" desc="$2" always="$3" bodyfile="$4"
  {
    echo "---"
    [ -n "$desc" ] && echo "description: $desc"
    echo "alwaysApply: $always"
    echo "---"
    echo
    cat "$bodyfile"
  } > "$out"
}

# --- 1. Always-on rules: operating rules + the trading ruleset -----------------------------
tmp="$(mktemp)"
cat "$REPO/CLAUDE.md" > "$tmp"
emit_rule "$OUT/rules/000-operating-rules.mdc" "" "true" "$tmp"
fm_body "$REPO/rules/RULES.md" > "$tmp"
emit_rule "$OUT/rules/010-trading-ruleset.mdc" "" "true" "$tmp"
rm -f "$tmp"

# --- 2. Skills → description-triggered rules ------------------------------------------------
while IFS= read -r sk; do
  require_fm "$sk"
  name="$(fm_field "$sk" name)"; [ -n "$name" ] || name="$(basename "$(dirname "$sk")")"
  desc="$(fm_field "$sk" description)"
  tmpbody="$(mktemp)"; fm_body "$sk" > "$tmpbody"
  emit_rule "$OUT/rules/skill-${name}.mdc" "$desc" "false" "$tmpbody"
  rm -f "$tmpbody"
done < <(find "$REPO/.claude/skills" -name SKILL.md | sort)

# --- 3. Commands → .cursor/commands/*.md ----------------------------------------------------
while IFS= read -r cmd; do
  require_fm "$cmd"
  base="$(basename "$cmd")"
  desc="$(fm_field "$cmd" description)"
  { [ -n "$desc" ] && { echo "<!-- $desc -->"; echo; }
    fm_body "$cmd"; } > "$OUT/commands/$base"
done < <(find "$REPO/.claude/commands" -name '*.md' | sort)

# --- 4. Hooks — protect-paths in both harnesses ---------------------------------------------
cat > "$OUT/hooks.json" <<'JSON'
{
  "version": 1,
  "hooks": {
    "beforeShellExecution": [
      { "command": "cd \"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\" && bash ./.claude/hooks/protect-paths.sh", "timeout": 15, "failClosed": true }
    ],
    "beforeReadFile": [],
    "afterFileEdit": [
      { "command": "cd \"$(git rev-parse --show-toplevel 2>/dev/null || pwd)\" && bash ./.claude/hooks/protect-paths.sh", "timeout": 15, "failClosed": true }
    ]
  }
}
JSON

# --- 5. MCP — ONLY robinhood-trading (Cursor caps ~40 active tools; Robinhood is ~40 alone) --
cat > "$OUT/mcp.json" <<'JSON'
{
  "//": "Only the Robinhood agentic-trading server. Cursor caps ~40 active tools across ALL servers and Robinhood alone is ~40 — do not add more servers to this project. OAuth happens in Cursor (Settings -> Tools & MCPs -> Connect); no keys live anywhere in this repo.",
  "mcpServers": {
    "robinhood-trading": {
      "type": "http",
      "url": "https://agent.robinhood.com/mcp/trading"
    }
  }
}
JSON

# --- 6. AGENTS.md — Cursor reads it natively ------------------------------------------------
AGENTS_OUT="$REPO/AGENTS.md"
[ "$CHECK" = 1 ] && AGENTS_OUT="$(dirname "$OUT")/AGENTS.md"
{
  echo "<!-- GENERATED by scripts/gen-cursor.sh — edit CLAUDE.md and run 'make cursor'. -->"
  echo
  cat "$REPO/CLAUDE.md"
  cat <<'MAP'

---

## Where things live (for agents)

| Need | Location |
|------|----------|
| The ruleset (canonical, versioned) | `rules/RULES.md` (mirrored always-on in `.cursor/rules/010-trading-ruleset.mdc`) |
| Gate constants + shadow/live flag | `config/limits.json` (human-only) |
| The pipeline CLI | `uv run rht …` (`src/rh_options/`) |
| Playbooks | `.claude/skills/` — mirrored as `.cursor/rules/skill-*.mdc` |
| Lifecycle commands | `.claude/commands/` — mirrored in `.cursor/commands/` |
| Trade evidence | `data/` (journal, tickets, validations, opinions, IV history) |
| Lessons & decisions | `knowledge/` |
| Self-checks | `make validate` · `make test` · regenerate this bundle: `make cursor` |
MAP
} > "$AGENTS_OUT"

# --- check mode ------------------------------------------------------------------------------
if [ "$CHECK" = 1 ]; then
  drift=0
  diff -rq "$REPO/.cursor" "$OUT" >/dev/null 2>&1 || drift=1
  diff -q "$REPO/AGENTS.md" "$AGENTS_OUT" >/dev/null 2>&1 || drift=1
  rm -rf "$(dirname "$OUT")"
  if [ "$drift" = 0 ]; then
    echo "✓ .cursor/ + AGENTS.md are up to date"
    exit 0
  fi
  echo "✗ .cursor/ or AGENTS.md is stale — run 'make cursor' and commit" >&2
  exit 1
fi
echo "✓ generated .cursor/ ($(find "$OUT" -type f | wc -l | tr -d ' ') files) + AGENTS.md"
